### PR TITLE
update taxa to mondo requirements

### PR DESCRIPTION
**Pull request by katiermullen**

### CODE REVIEW

**Comment by matentzn** [comment]
@glass-ships the original list you used, was it just what I provided for you? Or did you mix in Monarch requirements already?

**Comment by glass-ships** [comment]
the list you provided contained all 4 monarch requirements. I also added aspergillus nidulans which was not in the list you provided, but was in the original list

**Comment by matentzn** [comment]
Can you tell me all 5 Monarch requirements? The ids I mean? I will add them back.

**Comment by glass-ships** [comment]
https://github.com/monarch-initiative/ncbi-gene/commit/371d607ee7df78c3ba19c29f0784675da324c5ba

9615, 9913, 9823, 9031, and 227321 are already in the new list. the first four were included in yours, the last is the only one that was missing, which i already added.

**Comment by matentzn** [comment]
Thx. Made sure all 5 are present, this is ready to merge then.

**Review by glass-ships — APPROVED** [review]

**Pull request merged**
